<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>bin\Debug\net8.0-windows\resimler\Teklif-Belgesi.ico</ApplicationIcon>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="viewModel\**" />
    <EmbeddedResource Remove="viewModel\**" />
    <None Remove="viewModel\**" />
    <Page Remove="viewModel\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="resimler\arkaplan.png" />
    <None Remove="resimler\liya_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.2.0" />
    <PackageReference Include="itext7" Version="9.2.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="resimler\arkaplan.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="resimler\liya_logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
	 <None Include="pdf_templates\*.pdf">
       <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	 </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0-windows\resimler\Teklif-Belgesi.ico" />
  </ItemGroup>


</Project>
